// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenIddict.AuthorizationServer.Context;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace OpenIddict.AuthorizationServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClientId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClientType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ConsentType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Permissions")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Requirements")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Settings")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("OpenIdApplications");
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Scopes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Subject")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("OpenIdAuthorizations");
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdScope", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Resources")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("OpenIdScopes");
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Payload")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Properties")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Status")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Subject")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AuthorizationId");

                    b.ToTable("OpenIdTokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Permissions")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Requirements")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Settings")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Scopes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Resources")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Name\" IS NOT NULL");

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Payload")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("\"ReferenceId\" IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdAuthorization", b =>
                {
                    b.HasOne("OpenIddict.AuthorizationServer.Model.OpenIdApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdToken", b =>
                {
                    b.HasOne("OpenIddict.AuthorizationServer.Model.OpenIdApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.AuthorizationServer.Model.OpenIdAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.AuthorizationServer.Model.OpenIdAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
